name: PrivateStorage
version: ${project.version}
author: TheBusyBiscuit
description: 此插件為繁體翻譯版, 原作者"TheBusyBiscuit".
main: io.github.thebusybiscuit.privatestorage.PrivateStorage
api-version: 1.14

depend: [Slimefun]

permissions:
  PrivateStorage.bypass:
    description: Allows to open all Safes
    default: false