name: PrivateStorage
version: ${project.version}
author: TheBusyBiscuit
description: 黏液科技附加 私人倉庫 繁體翻譯版.
main: io.github.thebusybiscuit.privatestorage.PrivateStorage
api-version: 1.14

depend: [Slimefun]

permissions:
  PrivateStorage.bypass:
    description: Allows to open all Safes
    default: false